--liquibase formatted sql

--changeset Sameh.Adel:create-customer-table dbms:postgresql splitStatements:false failOnError:true

CREATE TABLE CUSTOMER (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(255) UNIQUE NOT NULL,
    ADDRESS_ZIP_CODE VARCHAR(255),
    ADDRESS_BUILDING_NUMBER VARCHAR(255),
    ADDRESS_STREET VARCHAR(255),
    ADDRESS_CITY VARCHAR(255),
    ADDRESS_REGION VARCHAR(255),
    ADDRESS_COUNTRY VARCHAR(255),
    IS_ACTIVE BOOLEAN NOT NULL,
    IS_BLOCKED BOOLEAN NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP
);

CREATE SEQUENCE CUSTOMER_ID_SEQ START WITH 1 INCREMENT BY 1;